#!/usr/bin/env bash
# This script installs nginx on the server and configures it to display 'Hello World!'

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx


# Create a new configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
	root /var/www/html;
	index index.html
	server_name _;
	location / {
        add_header Content-Type text/plain;
    }
}" > /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html
# Enable the new configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart nginx
service nginx restart
