#!/usr/bin/env bash
# This script installs nginx on the server and configures it to display 'Hello World!'

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx

# Remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a new configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location / {
        try_files \$uri \$uri/ =404;
        add_header Content-Type text/plain;
    }
}" > /etc/nginx/sites-available/hello

# Enable the new configuration file
ln -s /etc/nginx/sites-available/hello /etc/nginx/sites-enabled/

# Restart nginx
service nginx restart
