#!/usr/bin/env bash
# This script installs nginx on the server and configures it to display 'Hello World!'

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx


echo "Hello World!" > /var/www/html/index.html

# Restart nginx
service nginx restart
