#!/usr/bin/env bash
# This script configures nginx to redirect /redirect_me to another page

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx

# Remove the default nginx configuration file
echo 'Hello World!' | tee /var/www/html/index.nginx-debian.html > /dev/null

# Create a new configuration file with a redirection
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect

# Enable the new configuration file
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Termnate all port80 connections
fuser -k 80/tcp

# Restart nginx
service nginx restart
