#!/usr/bin/env bash
# This script configures nginx to redirect /redirect_me to another page

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx

# Remove the default nginx configuration file
# rm /etc/nginx/sites-enabled/default

ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Create a new configuration file with a redirection
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect

# Enable the new configuration file
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Termnate all port80 connections
fuser -k 80/tcp

# Restart nginx
service nginx restart


# apt-get -y update
# apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# echo 'Hello World!' > /var/www/html/index.nginx-debian.html
# sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# service nginx start
