#!/usr/bin/env bash
# This script installs nginx, configures it to listen on port 80, sets up a default page, adds a redirection, and a custom 404 page

# Update the package lists for upgrades and new package installations
apt-get update

# Install nginx
apt-get install -y nginx

# Remove the default nginx configuration
rm /etc/nginx/sites-enabled/default

# Create a new default nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
        add_header Content-Type text/plain;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Enable the new configuration
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Create a new index.html file
echo "Hello World!" > /var/www/html/index.html

# Create a new 404.html file
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Restart nginx
service nginx restart
