#!/usr/bin/env bash

# Install software-properties-common
# sudo apt-get install --no-install-recommends software-properties-common

# Add the HAProxy PPA
# sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

# Update the package list and install the specific version of HAProxy
sudo apt-get update
sudo apt-get install haproxy -y

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo systemctl enable haproxy

# Define the HAProxy configuration
CONFIG="
frontend http_front
    bind *:80
	mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 514039-web-01 34.234.193.86:80 check
    server 514039-web-02 54.90.40.86:80 check
"

# Write the configuration
echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart
