#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server.
# Distribute requests using a roundrobin algorithm

apt update
apt install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy

echo "
backend web_backend
	balance roundrobin
	server 512726-web-01 52.91.118.253:80 check
	server 512726-web-02 35.153.16.72:80 check
frontend http
		bind *:80
		mode http
		default_backend web_backend" >> /etc/haproxy/haproxy.cfg

service haproxy restart
