#!/usr/bin/env bash
# This script ensures that Nginx is running and listening on port 80
service nginx start
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
