#!/usr/bin/env bash
# Run Nginx as nginx user
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
