#!/usr/bin/env bash
# Bash script to reload Gunicorn in a graceful way

# Get the PID of Gunicorn master processes
PIDS=$(pgrep -f gunicorn)

# Check if Gunicorn is running
if [ -z "$PIDS" ]; then
    exit 1
fi

# Send HUP signal to Gunicorn master processes
for PID in $PIDS
do
    kill -HUP "$PID"
done
